### ISSUE TITLE
Structured Field?

### ISSUE THREAD

**Issue by mnot** [ietf-wg-httpapi/link-template#1]
Emerging best practice is to use [Structured Fields](https://www.rfc-editor.org/rfc/rfc8941.html) for new headers, so that parsing is well-defined.

Arguments for sticking with a `Link`-like syntax:

* Consistence with `Link` (IMO a very poor justification)
* Reuse of `Link` parsers / other software (it's not well-defined, tho)
* ???

**Comment by mnot** [comment]
We could also talk about creating a SF version of `Link` (maybe `Links`?).

**Comment by handrews** [comment]
> We could also talk about creating a SF version of Link (maybe Links?).

Matching SF `Links` and `Link-Templates` headers would be appealing.

**Comment by mnot** [comment]
In the meantime (or maybe before ;) --
  https://httpwg.org/http-extensions/draft-ietf-httpbis-retrofit.html#name-links
