### ISSUE TITLE
Non-ASCII content

### ISSUE THREAD

**Issue by mnot** [ietf-wg-httpapi/link-template#9]
In Web Linking, target attributes (e.g., `title`) are [allowed to contain unicode](https://www.rfc-editor.org/rfc/rfc8288.html#section-2.2).

The current serialization of links in `Link-Template` only allows serialisation as Strings, which are ASCII-only.

**Comment by mnot** [comment]
Let's look at the most obvious case for this -- `title`. Taking an example from the spec, you could imagine:

~~~ http-message
Link-Template: "/books/{book_id}/author";
               rel="author"; anchor="#{book_id}"
               title=%"percent encoded unicode here"
~~~

The thing is, if this is a link template, _the title is not going to be static._ In fact, I can't think of any situation where any content in a user-visible isn't going to be dynamic.

We could add the capability to use templates in non-URI Parameters. However, that begs the question -- if the person creating the field already has that information, and already has it associated with `{book_id}`, what good does it do to tell them about it in the `Link-Template` field?

To be clear, it would be very easy to say that target attributes can be either Strings or Display Strings. I just don't see much of a use case for serialising them in `Link-Template` (whether or not they have non-ASCII content).

Thoughts?

**Comment by mnot** [comment]
... although `Link-Template` has another use case -- as a structured replacement for `Link` (i.e., you don't use any templates, despite the name). So we probably do need to accommodate non-ASCII content in parameters.

I'll create a PR that tries to address this.

**Comment by richsalz** [comment]
Is this the "last" issue?
